sudo: required
language: node_js
node_js: 8.0

cache: npm

before_install: npm i -g npm@6.5.0
install:
  - npm ci
  - npm i polymer-cli

before_script:
  - tslint -c ./tslint.json --project ./

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - xvfb-run polymer test --npm --expanded

dist: trusty
