sudo: required
language: node_js
node_js: 8.0

cache:
  directories:
    - node_modules

install:
  - npm install
  - tsc

before_script:
  - tslint -c ./tslint.json --project ./

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - xvfb-run polymer test

dist: trusty
