language: node_js
node_js: stable
sudo: required
install:
- npm install -g polymer-cli
before_script:
- polymer install
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

script: xvfb-run polymer test
dist: trusty
