language: node_js
node_js: stable
sudo: required
install:
- npm install
before_script:
- polymer install
- polymer lint --rules polymer-3 --input *.html
- eslint . --ext js,html --ignore-path .gitignore
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

script: xvfb-run polymer test
dist: trusty
