/**
@license
Copyright 2018 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {css} from 'lit-element';
/**
 !Note: This file is autogenerated and any changes here may be silently overridden
*/
export const style = css`
  :host {
    --app-drawer-width: 16rem;
    --app-toolbar-height: 3.6rem;
    --app-header-background-color: var(--mdc-theme-primary);
    --app-header-text-color: var(--mdc-theme-on-primary);
    --app-header-selected-color: var(--mdc-theme-on-primary);
    --app-drawer-collapsed-width: 4rem;
    --app-drawer-background-color: #162b41;
    --app-drawer-background-hover-color: #20354b;
    --exmg-paper-sidemenu-background: var(--app-drawer-background-color);
    --exmg-paper-sidemenu-group-text-color: rgba(255, 255, 255, 0.7);
    --exmg-paper-sidemenu-group-title: rgba(255, 255, 255, 0.7);
    --exmg-paper-sidemenu-item-text-color: rgba(255, 255, 255, 0.7);
    --exmg-paper-sidemenu-menu-footer-background-color: #162b41;
    --exmg-paper-sidemenu-menu-border-color: rgba(255, 255, 255, 0.12);
    --exmg-paper-sidemenu-icon-color: rgba(255, 255, 255, 0.9);
    --exmg-paper-sidemenu-badge-background-color: var(--mdc-theme-primary);
    --exmg-paper-sidemenu-badge-text-color: var(--mdc-theme-on-primary);
    --exmg-paper-sidemenu-hover-background-color: var(--app-drawer-background-hover-color);
    --exmg-paper-sidemenu-selected-text-color: var(--mdc-theme-primary);
    --exmg-paper-sidemenu-menu-header-background-color: var(--app-drawer-background-color);
    --exmg-paper-sidemenu-hover-background-color: var(--app-drawer-background-hover-color);
    --exmg-paper-sidemenu-selected-text-color: var(--mdc-theme-primary);
  }
  :host app-drawer {
    background: var(--exmg-paper-sidemenu-background);
  }
`;
export default style;
