/**
@license
Copyright 2018 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {css} from 'lit-element';
/**
 !Note: This file is autogenerated and any changes here may be silently overridden
*/
export const style = css`
  .mdc-typography {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-font-family, Roboto, sans-serif);
  }
  .mdc-typography--headline1 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-headline1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 6rem;
    font-size: var(--mdc-typography-headline1-font-size, 6rem);
    line-height: 6rem;
    line-height: var(--mdc-typography-headline1-line-height, 6rem);
    font-weight: 300;
    font-weight: var(--mdc-typography-headline1-font-weight, 300);
    letter-spacing: -0.015625em;
    letter-spacing: var(--mdc-typography-headline1-letter-spacing, -0.015625em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-headline1-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-headline1-text-transform, inherit);
  }
  .mdc-typography--headline2 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-headline2-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 3.75rem;
    font-size: var(--mdc-typography-headline2-font-size, 3.75rem);
    line-height: 3.75rem;
    line-height: var(--mdc-typography-headline2-line-height, 3.75rem);
    font-weight: 300;
    font-weight: var(--mdc-typography-headline2-font-weight, 300);
    letter-spacing: -0.0083333333em;
    letter-spacing: var(--mdc-typography-headline2-letter-spacing, -0.0083333333em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-headline2-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-headline2-text-transform, inherit);
  }
  .mdc-typography--headline3 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-headline3-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 3rem;
    font-size: var(--mdc-typography-headline3-font-size, 3rem);
    line-height: 3.125rem;
    line-height: var(--mdc-typography-headline3-line-height, 3.125rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-headline3-font-weight, 400);
    letter-spacing: normal;
    letter-spacing: var(--mdc-typography-headline3-letter-spacing, normal);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-headline3-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-headline3-text-transform, inherit);
  }
  .mdc-typography--headline4 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-headline4-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 2.125rem;
    font-size: var(--mdc-typography-headline4-font-size, 2.125rem);
    line-height: 2.5rem;
    line-height: var(--mdc-typography-headline4-line-height, 2.5rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-headline4-font-weight, 400);
    letter-spacing: 0.0073529412em;
    letter-spacing: var(--mdc-typography-headline4-letter-spacing, 0.0073529412em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-headline4-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-headline4-text-transform, inherit);
  }
  .mdc-typography--headline5 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-headline5-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 1.5rem;
    font-size: var(--mdc-typography-headline5-font-size, 1.5rem);
    line-height: 2rem;
    line-height: var(--mdc-typography-headline5-line-height, 2rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-headline5-font-weight, 400);
    letter-spacing: normal;
    letter-spacing: var(--mdc-typography-headline5-letter-spacing, normal);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-headline5-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-headline5-text-transform, inherit);
  }
  .mdc-typography--headline6 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 1.25rem;
    font-size: var(--mdc-typography-headline6-font-size, 1.25rem);
    line-height: 2rem;
    line-height: var(--mdc-typography-headline6-line-height, 2rem);
    font-weight: 500;
    font-weight: var(--mdc-typography-headline6-font-weight, 500);
    letter-spacing: 0.0125em;
    letter-spacing: var(--mdc-typography-headline6-letter-spacing, 0.0125em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-headline6-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-headline6-text-transform, inherit);
  }
  .mdc-typography--subtitle1 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-subtitle1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 1rem;
    font-size: var(--mdc-typography-subtitle1-font-size, 1rem);
    line-height: 1.75rem;
    line-height: var(--mdc-typography-subtitle1-line-height, 1.75rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-subtitle1-font-weight, 400);
    letter-spacing: 0.009375em;
    letter-spacing: var(--mdc-typography-subtitle1-letter-spacing, 0.009375em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-subtitle1-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-subtitle1-text-transform, inherit);
  }
  .mdc-typography--subtitle2 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-subtitle2-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 0.875rem;
    font-size: var(--mdc-typography-subtitle2-font-size, 0.875rem);
    line-height: 1.375rem;
    line-height: var(--mdc-typography-subtitle2-line-height, 1.375rem);
    font-weight: 500;
    font-weight: var(--mdc-typography-subtitle2-font-weight, 500);
    letter-spacing: 0.0071428571em;
    letter-spacing: var(--mdc-typography-subtitle2-letter-spacing, 0.0071428571em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-subtitle2-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-subtitle2-text-transform, inherit);
  }
  .mdc-typography--body1 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 1rem;
    font-size: var(--mdc-typography-body1-font-size, 1rem);
    line-height: 1.5rem;
    line-height: var(--mdc-typography-body1-line-height, 1.5rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-body1-font-weight, 400);
    letter-spacing: 0.03125em;
    letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-body1-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-body1-text-transform, inherit);
  }
  .mdc-typography--body2 {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-body2-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 0.875rem;
    font-size: var(--mdc-typography-body2-font-size, 0.875rem);
    line-height: 1.25rem;
    line-height: var(--mdc-typography-body2-line-height, 1.25rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-body2-font-weight, 400);
    letter-spacing: 0.0178571429em;
    letter-spacing: var(--mdc-typography-body2-letter-spacing, 0.0178571429em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-body2-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-body2-text-transform, inherit);
  }
  .mdc-typography--caption {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-caption-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 0.75rem;
    font-size: var(--mdc-typography-caption-font-size, 0.75rem);
    line-height: 1.25rem;
    line-height: var(--mdc-typography-caption-line-height, 1.25rem);
    font-weight: 400;
    font-weight: var(--mdc-typography-caption-font-weight, 400);
    letter-spacing: 0.0333333333em;
    letter-spacing: var(--mdc-typography-caption-letter-spacing, 0.0333333333em);
    text-decoration: inherit;
    text-decoration: var(--mdc-typography-caption-text-decoration, inherit);
    text-transform: inherit;
    text-transform: var(--mdc-typography-caption-text-transform, inherit);
  }
  .mdc-typography--button {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 0.875rem;
    font-size: var(--mdc-typography-button-font-size, 0.875rem);
    line-height: 2.25rem;
    line-height: var(--mdc-typography-button-line-height, 2.25rem);
    font-weight: 500;
    font-weight: var(--mdc-typography-button-font-weight, 500);
    letter-spacing: 0.0892857143em;
    letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857143em);
    text-decoration: none;
    text-decoration: var(--mdc-typography-button-text-decoration, none);
    text-transform: uppercase;
    text-transform: var(--mdc-typography-button-text-transform, uppercase);
  }
  .mdc-typography--overline {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-family: Roboto, sans-serif;
    font-family: var(--mdc-typography-overline-font-family, var(--mdc-typography-font-family, Roboto, sans-serif));
    font-size: 0.75rem;
    font-size: var(--mdc-typography-overline-font-size, 0.75rem);
    line-height: 2rem;
    line-height: var(--mdc-typography-overline-line-height, 2rem);
    font-weight: 500;
    font-weight: var(--mdc-typography-overline-font-weight, 500);
    letter-spacing: 0.1666666667em;
    letter-spacing: var(--mdc-typography-overline-letter-spacing, 0.1666666667em);
    text-decoration: none;
    text-decoration: var(--mdc-typography-overline-text-decoration, none);
    text-transform: uppercase;
    text-transform: var(--mdc-typography-overline-text-transform, uppercase);
  }
  :root {
    --mdc-theme-primary: #6200ee;
    --mdc-theme-secondary: #018786;
    --mdc-theme-background: #fff;
    --mdc-theme-surface: #fff;
    --mdc-theme-error: #b00020;
    --mdc-theme-on-primary: #fff;
    --mdc-theme-on-secondary: #fff;
    --mdc-theme-on-surface: #000;
    --mdc-theme-on-error: #fff;
    --mdc-theme-text-primary-on-background: rgba(0, 0, 0, 0.87);
    --mdc-theme-text-secondary-on-background: rgba(0, 0, 0, 0.54);
    --mdc-theme-text-hint-on-background: rgba(0, 0, 0, 0.38);
    --mdc-theme-text-disabled-on-background: rgba(0, 0, 0, 0.38);
    --mdc-theme-text-icon-on-background: rgba(0, 0, 0, 0.38);
    --mdc-theme-text-primary-on-light: rgba(0, 0, 0, 0.87);
    --mdc-theme-text-secondary-on-light: rgba(0, 0, 0, 0.54);
    --mdc-theme-text-hint-on-light: rgba(0, 0, 0, 0.38);
    --mdc-theme-text-disabled-on-light: rgba(0, 0, 0, 0.38);
    --mdc-theme-text-icon-on-light: rgba(0, 0, 0, 0.38);
    --mdc-theme-text-primary-on-dark: white;
    --mdc-theme-text-secondary-on-dark: rgba(255, 255, 255, 0.7);
    --mdc-theme-text-hint-on-dark: rgba(255, 255, 255, 0.5);
    --mdc-theme-text-disabled-on-dark: rgba(255, 255, 255, 0.5);
    --mdc-theme-text-icon-on-dark: rgba(255, 255, 255, 0.5);
  }
  .mdc-theme--primary {
    color: #6200ee !important;
    color: var(--mdc-theme-primary, #6200ee) !important;
  }
  .mdc-theme--secondary {
    color: #018786 !important;
    color: var(--mdc-theme-secondary, #018786) !important;
  }
  .mdc-theme--background {
    background-color: #fff;
    background-color: var(--mdc-theme-background, #fff);
  }
  .mdc-theme--surface {
    background-color: #fff;
    background-color: var(--mdc-theme-surface, #fff);
  }
  .mdc-theme--error {
    color: #b00020 !important;
    color: var(--mdc-theme-error, #b00020) !important;
  }
  .mdc-theme--on-primary {
    color: #fff !important;
    color: var(--mdc-theme-on-primary, #fff) !important;
  }
  .mdc-theme--on-secondary {
    color: #fff !important;
    color: var(--mdc-theme-on-secondary, #fff) !important;
  }
  .mdc-theme--on-surface {
    color: #000 !important;
    color: var(--mdc-theme-on-surface, #000) !important;
  }
  .mdc-theme--on-error {
    color: #fff !important;
    color: var(--mdc-theme-on-error, #fff) !important;
  }
  .mdc-theme--text-primary-on-background {
    color: rgba(0, 0, 0, 0.87) !important;
    color: var(--mdc-theme-text-primary-on-background, rgba(0, 0, 0, 0.87)) !important;
  }
  .mdc-theme--text-secondary-on-background {
    color: rgba(0, 0, 0, 0.54) !important;
    color: var(--mdc-theme-text-secondary-on-background, rgba(0, 0, 0, 0.54)) !important;
  }
  .mdc-theme--text-hint-on-background {
    color: rgba(0, 0, 0, 0.38) !important;
    color: var(--mdc-theme-text-hint-on-background, rgba(0, 0, 0, 0.38)) !important;
  }
  .mdc-theme--text-disabled-on-background {
    color: rgba(0, 0, 0, 0.38) !important;
    color: var(--mdc-theme-text-disabled-on-background, rgba(0, 0, 0, 0.38)) !important;
  }
  .mdc-theme--text-icon-on-background {
    color: rgba(0, 0, 0, 0.38) !important;
    color: var(--mdc-theme-text-icon-on-background, rgba(0, 0, 0, 0.38)) !important;
  }
  .mdc-theme--text-primary-on-light {
    color: rgba(0, 0, 0, 0.87) !important;
    color: var(--mdc-theme-text-primary-on-light, rgba(0, 0, 0, 0.87)) !important;
  }
  .mdc-theme--text-secondary-on-light {
    color: rgba(0, 0, 0, 0.54) !important;
    color: var(--mdc-theme-text-secondary-on-light, rgba(0, 0, 0, 0.54)) !important;
  }
  .mdc-theme--text-hint-on-light {
    color: rgba(0, 0, 0, 0.38) !important;
    color: var(--mdc-theme-text-hint-on-light, rgba(0, 0, 0, 0.38)) !important;
  }
  .mdc-theme--text-disabled-on-light {
    color: rgba(0, 0, 0, 0.38) !important;
    color: var(--mdc-theme-text-disabled-on-light, rgba(0, 0, 0, 0.38)) !important;
  }
  .mdc-theme--text-icon-on-light {
    color: rgba(0, 0, 0, 0.38) !important;
    color: var(--mdc-theme-text-icon-on-light, rgba(0, 0, 0, 0.38)) !important;
  }
  .mdc-theme--text-primary-on-dark {
    color: #fff !important;
    color: var(--mdc-theme-text-primary-on-dark, white) !important;
  }
  .mdc-theme--text-secondary-on-dark {
    color: rgba(255, 255, 255, 0.7) !important;
    color: var(--mdc-theme-text-secondary-on-dark, rgba(255, 255, 255, 0.7)) !important;
  }
  .mdc-theme--text-hint-on-dark {
    color: rgba(255, 255, 255, 0.5) !important;
    color: var(--mdc-theme-text-hint-on-dark, rgba(255, 255, 255, 0.5)) !important;
  }
  .mdc-theme--text-disabled-on-dark {
    color: rgba(255, 255, 255, 0.5) !important;
    color: var(--mdc-theme-text-disabled-on-dark, rgba(255, 255, 255, 0.5)) !important;
  }
  .mdc-theme--text-icon-on-dark {
    color: rgba(255, 255, 255, 0.5) !important;
    color: var(--mdc-theme-text-icon-on-dark, rgba(255, 255, 255, 0.5)) !important;
  }
  .mdc-theme--primary-bg {
    background-color: #6200ee !important;
    background-color: var(--mdc-theme-primary, #6200ee) !important;
  }
  .mdc-theme--secondary-bg {
    background-color: #018786 !important;
    background-color: var(--mdc-theme-secondary, #018786) !important;
  }
  :host {
    height: 100%;
    width: var(--exmg-paper-sidemenu-sidth);
    background: var(--exmg-paper-sidemenu-background, white);
    box-shadow: 2px 0 2px 0 rgba(0, 0, 0, 0.1);
    transition: all 0.3s ease;
    overflow: hidden;
    color: var(--default-paper-sidemenu-text-color);
    flex: 1;
    flex-basis: 1e-9px;
    display: flex;
    flex-direction: column;
  }
  :host([collapsed]) hr {
    height: 1px;
  }
  paper-listbox {
    padding: 0;
    background: var(--exmg-paper-sidemenu-background);
  }
  :host([collapsed]) paper-item .title {
    opacity: 0;
    max-width: 0px;
  }
  .menu-body {
    flex: 1;
    flex-basis: 1e-9px;
    overflow: auto;
  }
  .menu-footer {
    border-top: 1px solid var(--exmg-paper-sidemenu-menu-border-color, #ddd);
    background: var(--exmg-paper-sidemenu-menu-footer-background-color, #f9faf9);
    height: 48px;
    display: flex;
    justify-content: flex-end;
    align-items: center;
  }
  :host([collapsed][footer-item]) .menu-footer {
    min-height: 94px;
    flex-direction: column;
  }
  .menu-footer button {
    cursor: pointer;
    background: none;
    border: none;
    height: 100%;
    padding: 0 8px;
    outline: none;
  }
  .menu-footer svg {
    transition: transform 0.3s ease;
    transform: rotate(0deg);
    justify-content: flex-end;
  }
  .menu-footer svg {
    margin: 0 4px;
    fill: var(--exmg-paper-sidemenu-icon-color, rgba(0, 0, 0, var(--dark-secondary-opacity)));
  }
  :host([narrow]) .menu-footer {
    display: none !important;
  }
  :host([collapsed]) .menu-footer {
    display: flex;
    justify-content: center;
    align-items: center;
  }
  :host([collapsed]) .menu-group {
    padding: 12px 0;
  }
  :host([collapsed]) .menu-group-title {
    height: 0;
    padding: 0;
    margin-bottom: 10px;
  }
  :host([collapsed]) .menu-footer svg {
    transform: rotate(180deg);
  }
`;
export default style;
