export const _items = [
  {
    header: 'Round 1',
    items: [
      {
        id: 0,
        nextid: 8,
        hasWon: 'player_0',
        hasStarted: true,
        playerOne: {
          playerId: 'player_0',
          name: 'Stefano Pinna',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_1',
          name: 'Anatoliy Shcherbatykh',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 1,
        hasWon: 'player_2',
        nextid: 8,
        hasStarted: true,
        playerOne: {
          playerId: 'player_2',
          name: 'Alia Baird',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_3',
          name: 'Oskar Nash',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 2,
        nextid: 9,
        hasWon: 'player_5',
        hasStarted: true,
        playerOne: {
          playerId: 'player_4',
          name: 'Bianka Hebert',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_5',
          name: 'Raja Ford',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 3,
        nextid: 9,
        hasWon: 'player_6',
        hasStarted: true,
        playerOne: {
          playerId: 'player_6',
          name: 'Keeva Washington',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_7',
          name: 'Daniela Bryan',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 4,
        nextid: 10,
        hasWon: 'player_8',
        hasStarted: true,
        playerOne: {
          playerId: 'player_8',
          name: 'Alexander Greaves',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_9',
          name: 'Mariyam Broughton',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 5,
        hasWon: 'player_11',
        nextid: 10,
        hasStarted: true,
        playerOne: {
          playerId: 'player_10',
          name: 'Alia Baird',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_11',
          name: 'Oskar Nash',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 6,
        nextid: 11,
        hasWon: 'player_13',
        hasStarted: true,
        playerOne: {
          playerId: 'player_12',
          name: 'Bianka Hebert',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_13',
          name: 'Raja Ford',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 7,
        nextid: 11,
        hasWon: 'player_15',
        hasStarted: true,
        playerOne: {
          playerId: 'player_14',
          name: 'Keeva Washington',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_15',
          name: 'Daniela Bryan',
          totalPoints: 30,
          score: 2,
        },
      },
    ],
  },
  {
    header: 'Round 2',
    items: [
      {
        id: 8,
        nextid: 12,
        hasWon: 'player_2',
        hasStarted: true,
        playerOne: {
          playerId: 'player_0',
          name: 'Stefano Pinna',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_2',
          name: 'Alia Baird',
          totalPoints: 50,
          score: 7,
        },
      },
      {
        id: 9,
        nextid: 12,
        hasWon: 'player_5',
        hasStarted: true,
        playerOne: {
          playerId: 'player_6',
          name: 'Keeva Washington',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_5',
          name: 'Raja Ford',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 10,
        nextid: 13,
        hasWon: 'player_11',
        hasStarted: true,
        playerOne: {
          playerId: 'player_8',
          name: 'Alexander Greaves',
          totalPoints: 50,
          score: 7,
        },
        playerTwo: {
          playerId: 'player_11',
          name: 'Oskar Nash',
          totalPoints: 30,
          score: 2,
        },
      },
      {
        id: 11,
        nextid: 13,
        hasWon: 'player_15',
        hasStarted: true,
        playerOne: {
          playerId: 'player_15',
          name: 'Daniela Bryan',
          totalPoints: 30,
          score: 2,
        },
        playerTwo: {
          playerId: 'player_13',
          name: 'Raja Ford',
          totalPoints: 30,
          score: 2,
        },
      },
    ],
  },
  {
    header: 'Round 3',
    items: [
      {
        id: 12,
        nextid: 14,
        hasWon: 'player_5',
        hasStarted: false,
        playerOne: {
          playerId: 'player_5',
          name: 'Raja Ford',
          totalPoints: 30,
          score: 2,
        },
        playerTwo: {
          playerId: 'player_2',
          name: 'Alia Baird',
          totalPoints: 50,
          score: 7,
        },
      },
      {
        id: 13,
        nextid: 14,
        hasWon: 'player_15',
        hasStarted: false,
        playerOne: {
          playerId: 'player_15',
          name: 'Daniela Bryan',
          totalPoints: 30,
          score: 2,
        },
        playerTwo: {
          playerId: 'player_11',
          name: 'Oskar Nash',
          totalPoints: 30,
          score: 2,
        },
      },
    ],
  },
  {
    header: 'Round 4',
    items: [
      {
        id: 14,
        nextid: '',
        hasWon: 'player_5',
        hasStarted: false,
        playerOne: {
          playerId: 'player_5',
          name: 'Raja Ford',
          totalPoints: 30,
          score: 2,
        },
        playerTwo: {
          playerId: 'player_15',
          name: 'Daniela Bryan',
          totalPoints: 30,
          score: 2,
        },
      },
    ],
  },
];
